/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.Font;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Pablo Ramirez
 */
public class Calculadora extends javax.swing.JFrame {

    private String cadenaNumeros = "";
    private String operacion = "nula";
    private double primerNumero, segundoNumero, resultado;
    private boolean activado = false;
    private boolean punto = true;
    private boolean esIgual = false;

    public Calculadora() {
        initComponents();
        this.setTitle("Calculadora");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        botonC = new javax.swing.JButton();
        botonDEL = new javax.swing.JButton();
        botonRaiz = new javax.swing.JButton();
        botonDivision = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonMultiplicar = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        botonRestar = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        botonSumar = new javax.swing.JButton();
        botonMasMenos = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        entradaNumeros = new javax.swing.JLabel();
        salidaNumeros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel.setLayout(new java.awt.GridLayout(5, 4));

        botonC.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });
        panel.add(botonC);

        botonDEL.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botonDEL.setText("←");
        botonDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDELActionPerformed(evt);
            }
        });
        panel.add(botonDEL);

        botonRaiz.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botonRaiz.setText("√ ");
        botonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRaizActionPerformed(evt);
            }
        });
        panel.add(botonRaiz);

        botonDivision.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botonDivision.setText("÷");
        botonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivisionActionPerformed(evt);
            }
        });
        panel.add(botonDivision);

        boton7.setBackground(new java.awt.Color(220, 220, 220));
        boton7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        panel.add(boton7);

        boton8.setBackground(new java.awt.Color(220, 220, 220));
        boton8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        panel.add(boton8);

        boton9.setBackground(new java.awt.Color(220, 220, 220));
        boton9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        panel.add(boton9);

        botonMultiplicar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botonMultiplicar.setText("x");
        botonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicarActionPerformed(evt);
            }
        });
        panel.add(botonMultiplicar);

        boton4.setBackground(new java.awt.Color(220, 220, 220));
        boton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        panel.add(boton4);

        boton5.setBackground(new java.awt.Color(220, 220, 220));
        boton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        panel.add(boton5);

        boton6.setBackground(new java.awt.Color(220, 220, 220));
        boton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        panel.add(boton6);

        botonRestar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botonRestar.setText("-");
        botonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestarActionPerformed(evt);
            }
        });
        panel.add(botonRestar);

        boton1.setBackground(new java.awt.Color(220, 220, 220));
        boton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        panel.add(boton1);

        boton2.setBackground(new java.awt.Color(220, 220, 220));
        boton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        panel.add(boton2);

        boton3.setBackground(new java.awt.Color(220, 220, 220));
        boton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        panel.add(boton3);

        botonSumar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botonSumar.setText("+");
        botonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumarActionPerformed(evt);
            }
        });
        panel.add(botonSumar);

        botonMasMenos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonMasMenos.setText("+/-");
        botonMasMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMasMenosActionPerformed(evt);
            }
        });
        panel.add(botonMasMenos);

        boton0.setBackground(new java.awt.Color(220, 220, 220));
        boton0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        panel.add(boton0);

        botonPunto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        panel.add(botonPunto);

        botonIgual.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        panel.add(botonIgual);

        entradaNumeros.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        entradaNumeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        entradaNumeros.setText("0");

        salidaNumeros.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        salidaNumeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        salidaNumeros.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salidaNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entradaNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salidaNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entradaNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed

        if (entradaNumeros.getText().equals("0")) {
            cadenaNumeros = "7";
        } else if (esIgual) {

            if (salidaNumeros.getText().contains("=")) {
                entradaNumeros.setText("");
                salidaNumeros.setText("");
                cadenaNumeros = "7";
                entradaNumeros.setFont(new Font("Dialog Bold", Font.BOLD, 36));

            } else {
                cadenaNumeros += "7";
            }

        } else {
            cadenaNumeros += "7";
        }

        cambiarTamanyo();
        activarBotones();

        entradaNumeros.setText(cadenaNumeros);
        activado = true;
        esIgual = false;


    }//GEN-LAST:event_boton7ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed

        if (entradaNumeros.getText().equals("0")) {
            cadenaNumeros = "0";
        } else if (esIgual) {

            if (salidaNumeros.getText().contains("=")) {
                entradaNumeros.setText("");
                salidaNumeros.setText("");
                cadenaNumeros = "0";
                this.entradaNumeros.setFont(new Font("Dialog Bold", Font.BOLD, 36));

            } else {
                cadenaNumeros += "0";
            }

        } else {
            cadenaNumeros += "0";
        }

        cambiarTamanyo();
        activarBotones();

        entradaNumeros.setText(cadenaNumeros);
        activado = true;
        esIgual = false;


    }//GEN-LAST:event_boton0ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed

        if (entradaNumeros.getText().equals("0")) {
            cadenaNumeros = "1";
        } else if (esIgual) {

            if (salidaNumeros.getText().contains("=")) {
                entradaNumeros.setText("");
                salidaNumeros.setText("");
                cadenaNumeros = "1";
                this.entradaNumeros.setFont(new Font("Dialog Bold", Font.BOLD, 36));

            } else {
                cadenaNumeros += "1";
            }

        } else {
            cadenaNumeros += "1";
        }

        cambiarTamanyo();
        activarBotones();

        entradaNumeros.setText(cadenaNumeros);
        activado = true;
        esIgual = false;


    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed

        if (entradaNumeros.getText().equals("0")) {
            cadenaNumeros = "2";
        } else if (esIgual) {

            if (salidaNumeros.getText().contains("=")) {
                entradaNumeros.setText("");
                salidaNumeros.setText("");
                cadenaNumeros = "2";
                this.entradaNumeros.setFont(new Font("Dialog Bold", Font.BOLD, 36));

            } else {
                cadenaNumeros += "2";
            }

        } else {
            cadenaNumeros += "2";
        }

        cambiarTamanyo();
        activarBotones();

        entradaNumeros.setText(cadenaNumeros);
        activado = true;
        esIgual = false;


    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed

        if (entradaNumeros.getText().equals("0")) {
            cadenaNumeros = "3";
        } else if (esIgual) {

            if (salidaNumeros.getText().contains("=")) {
                entradaNumeros.setText("");
                salidaNumeros.setText("");
                cadenaNumeros = "3";
                this.entradaNumeros.setFont(new Font("Dialog Bold", Font.BOLD, 36));

            } else {
                cadenaNumeros += "3";
            }

        } else {
            cadenaNumeros += "3";
        }

        cambiarTamanyo();
        activarBotones();

        entradaNumeros.setText(cadenaNumeros);
        activado = true;
        esIgual = false;


    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed

        if (entradaNumeros.getText().equals("0")) {
            cadenaNumeros = "4";
        } else if (esIgual) {

            if (salidaNumeros.getText().contains("=")) {
                entradaNumeros.setText("");
                salidaNumeros.setText("");
                cadenaNumeros = "4";
                this.entradaNumeros.setFont(new Font("Dialog Bold", Font.BOLD, 36));

            } else {
                cadenaNumeros += "4";
            }

        } else {
            cadenaNumeros += "4";
        }

        cambiarTamanyo();
        activarBotones();

        entradaNumeros.setText(cadenaNumeros);
        activado = true;
        esIgual = false;


    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed

        if (entradaNumeros.getText().equals("0")) {
            cadenaNumeros = "5";
        } else if (esIgual) {

            if (salidaNumeros.getText().contains("=")) {
                entradaNumeros.setText("");
                salidaNumeros.setText("");
                cadenaNumeros = "5";
                this.entradaNumeros.setFont(new Font("Dialog Bold", Font.BOLD, 36));

            } else {
                cadenaNumeros += "5";
            }

        } else {
            cadenaNumeros += "5";
        }

        cambiarTamanyo();
        activarBotones();

        entradaNumeros.setText(cadenaNumeros);
        activado = true;
        esIgual = false;


    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed

        if (entradaNumeros.getText().equals("0")) {
            cadenaNumeros = "6";
        } else if (esIgual) {

            if (salidaNumeros.getText().contains("=")) {
                entradaNumeros.setText("");
                salidaNumeros.setText("");
                cadenaNumeros = "6";
                this.entradaNumeros.setFont(new Font("Dialog Bold", Font.BOLD, 36));

            } else {
                cadenaNumeros += "6";
            }

        } else {
            cadenaNumeros += "6";
        }

        cambiarTamanyo();
        activarBotones();

        entradaNumeros.setText(cadenaNumeros);
        activado = true;
        esIgual = false;


    }//GEN-LAST:event_boton6ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed

        if (entradaNumeros.getText().equals("0")) {
            cadenaNumeros = "8";
        } else if (esIgual) {

            if (salidaNumeros.getText().contains("=")) {
                entradaNumeros.setText("");
                salidaNumeros.setText("");
                cadenaNumeros = "8";
                this.entradaNumeros.setFont(new Font("Dialog Bold", Font.BOLD, 36));

            } else {
                cadenaNumeros += "8";
            }

        } else {
            cadenaNumeros += "8";
        }

        cambiarTamanyo();
        activarBotones();
        entradaNumeros.setText(cadenaNumeros);
        activado = true;
        esIgual = false;


    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed

        if (entradaNumeros.getText().equals("0")) {
            cadenaNumeros = "9";
        } else if (esIgual) {

            if (salidaNumeros.getText().contains("=")) {
                entradaNumeros.setText("");
                salidaNumeros.setText("");
                cadenaNumeros = "9";
                this.entradaNumeros.setFont(new Font("Dialog Bold", Font.BOLD, 36));

            } else {
                cadenaNumeros += "9";

            }

        } else {
            cadenaNumeros += "9";

        }

        cambiarTamanyo();
        activarBotones();

        entradaNumeros.setText(cadenaNumeros);
        activado = true;
        esIgual = false;

    }//GEN-LAST:event_boton9ActionPerformed

    private void botonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumarActionPerformed
        if (activado && operacion.equals("nula")) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            salidaNumeros.setText(cadenaNumeros + " + ");
            operacion = "sumar";
            cadenaNumeros = "";
            punto = true;
            activado = false;
            esIgual = true;
        }


    }//GEN-LAST:event_botonSumarActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        int longitud = cadenaNumeros.length();

        if (operacion.equals("nula")) {

            if (longitud == 0) {
                entradaNumeros.setText("0");
                cadenaNumeros = "0";
                activarBotones();
                System.out.println("entra aqui");
            } else {
                entradaNumeros.setText(cadenaNumeros);
                System.out.println("nnuula");
            }
        } else if (operacion.equals("sumar")) {
            sumar();
        } else if (operacion.equals("restar")) {
            restar();
        } else if (operacion.equals("multiplicar")) {
            multiplicar();
        } else if (operacion.equals("dividir")) {
            dividir();
        }
        activado = true;
        esIgual = true;

    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestarActionPerformed
        if (activado && operacion.equals("nula")) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            salidaNumeros.setText(cadenaNumeros + " - ");
            operacion = "restar";
            cadenaNumeros = "";
            punto = true;
            activado = false;
        }
    }//GEN-LAST:event_botonRestarActionPerformed

    private void botonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicarActionPerformed
        if (activado && operacion.equals("nula")) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            salidaNumeros.setText(cadenaNumeros + " x ");
            operacion = "multiplicar";
            cadenaNumeros = "";
            punto = true;
            activado = false;
        }
    }//GEN-LAST:event_botonMultiplicarActionPerformed

    private void botonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivisionActionPerformed
        if (activado && operacion.equals("nula")) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            salidaNumeros.setText(cadenaNumeros + " / ");
            operacion = "dividir";
            cadenaNumeros = "";
            punto = true;
            activado = false;
        }
    }//GEN-LAST:event_botonDivisionActionPerformed

    private void botonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRaizActionPerformed
        if (activado && operacion.equals("nula")) {
            primerNumero = Double.parseDouble(cadenaNumeros);
            salidaNumeros.setText("sqrt(" + cadenaNumeros + ")");
            resultado = Math.round((Math.sqrt(primerNumero)) * 100.0) / 100.0;
            entradaNumeros.setText(String.format("% .2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            punto = true;

            activado = true;

            esIgual = true;
        }

    }//GEN-LAST:event_botonRaizActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed

        if (punto) {
            if (cadenaNumeros.equals("")) {
                cadenaNumeros = "0.";
            } else if (salidaNumeros.getText().contains("=") || esIgual) {
                salidaNumeros.setText("");
                cadenaNumeros = "0.";
                esIgual = false;
            } else {
                cadenaNumeros += ".";
            }
            entradaNumeros.setText(cadenaNumeros);
            activado = true;
            punto = false;

        }


    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonMasMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMasMenosActionPerformed
        if (cadenaNumeros != "") {
            if (cadenaNumeros.charAt(0) != '-') {
                cadenaNumeros = '-' + cadenaNumeros;
            } else {
                cadenaNumeros = cadenaNumeros.substring(1, cadenaNumeros.length());
            }
            entradaNumeros.setText(cadenaNumeros);
        }


    }//GEN-LAST:event_botonMasMenosActionPerformed

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        int longitud = cadenaNumeros.length();
        entradaNumeros.setText("0");
        salidaNumeros.setText("");
        operacion = "nula";
        cadenaNumeros = "";
        activado = true;
        punto = true;

        if (longitud == 0) {
            entradaNumeros.setText("0");
            cadenaNumeros = "0";
            activarBotones();
        }

    }//GEN-LAST:event_botonCActionPerformed

    private void botonDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDELActionPerformed
        int longitud = cadenaNumeros.length();

        if (longitud == 0) { //Cuando se ha dividido por cero

            entradaNumeros.setText("0");
            cadenaNumeros = "0";
            esIgual = false;

            activarBotones();
            //Cuando han introducido numeros

        } else {
            if (esIgual) { //Cuando se ha dado un resultado

                salidaNumeros.setText("");

            } else if (longitud == 1) {  //Cuando la cadena solo le queda SOLO un numero
                cadenaNumeros = "0";
            } else if (longitud > 1) {
                cadenaNumeros = cadenaNumeros.substring(0, longitud - 1);
            }
        }
        cambiarTamanyo();
        entradaNumeros.setText(cadenaNumeros);

    }//GEN-LAST:event_botonDELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    private void sumar() {
//        double segundoNumero;
        if (this.cadenaNumeros == "") {
            this.segundoNumero = this.primerNumero;
        } else {
            this.segundoNumero = Double.parseDouble(this.cadenaNumeros);
        }

        this.resultado = this.primerNumero + this.segundoNumero;
        this.salidaNumeros.setText(eliminaDecimales(this.primerNumero) + " + " + eliminaDecimales(this.segundoNumero) + " = ");
        this.entradaNumeros.setText(eliminaDecimales(this.resultado));
        this.cadenaNumeros = eliminaDecimales(this.resultado); //Se convierte el double a String
        this.operacion = "nula";

        this.punto = true;
    }

    private void restar() {

        if (this.cadenaNumeros == "") {
            this.segundoNumero = this.primerNumero;
        } else {
            this.segundoNumero = Double.parseDouble(this.cadenaNumeros);
        }
        this.salidaNumeros.setText("");
        this.resultado = this.primerNumero - this.segundoNumero;
        this.salidaNumeros.setText(eliminaDecimales(this.primerNumero) + " - " + eliminaDecimales(this.segundoNumero) + " = ");
//        entradaNumeros.setText(String.format("% .1f", resultado));
        this.entradaNumeros.setText(eliminaDecimales(this.resultado));
        this.cadenaNumeros = eliminaDecimales(this.resultado); //Se convierte el double a String
        this.operacion = "nula";
        this.punto = true;

    }

    private void multiplicar() {
        if (this.cadenaNumeros == "") {
            segundoNumero = primerNumero;
        } else {
            segundoNumero = Double.parseDouble(this.cadenaNumeros);
        }
        salidaNumeros.setText("");
        resultado = primerNumero * segundoNumero;
        salidaNumeros.setText(eliminaDecimales(primerNumero) + " x " + eliminaDecimales(segundoNumero) + " = ");
        this.entradaNumeros.setText(eliminaDecimales(this.resultado));
        cadenaNumeros = eliminaDecimales(resultado); //Se convierte el double a String
        operacion = "nula";
        punto = true;

    }

    private void dividir() {
        if (this.cadenaNumeros == "") {

            segundoNumero = primerNumero;
        } else {
            segundoNumero = Double.parseDouble(this.cadenaNumeros);
        }

        if (segundoNumero == 0) {
            entradaNumeros.setText("NoSeDividePor0");
            salidaNumeros.setText("");
            cadenaNumeros = "";
            operacion = "nula";
            this.botonDivision.setEnabled(false);
            this.botonMultiplicar.setEnabled(false);
            this.botonRestar.setEnabled(false);
            this.botonSumar.setEnabled(false);
            this.botonPunto.setEnabled(false);
            this.botonMasMenos.setEnabled(false);
            this.botonRaiz.setEnabled(false);
//            primerNumero = 0;
            //            segundoNumero = 0;
            System.out.println("llego");

        } else {
            salidaNumeros.setText("");
            resultado = primerNumero / segundoNumero;
            salidaNumeros.setText(eliminaDecimales(primerNumero) + " / " + eliminaDecimales(segundoNumero) + " = ");
            this.entradaNumeros.setText(eliminaDecimales(this.resultado));
            cadenaNumeros = eliminaDecimales(resultado); //Se convierte el double a String
            operacion = "nula";
        }

        punto = true;

    }

    private String eliminaDecimales(double resultado) {
        String retorno = "";
        retorno = Double.toString(resultado);

        if (resultado % 1 == 0) {
            retorno = retorno.substring(0, retorno.length() - 2);
        } else if (retorno.length() > 14) {
            this.entradaNumeros.setFont(new Font("Dialog Bold", Font.BOLD, 28));
        }

        return retorno;
    }

    private boolean activarBotones() {
        this.botonDivision.setEnabled(true);
        this.botonMultiplicar.setEnabled(true);
        this.botonRestar.setEnabled(true);
        this.botonSumar.setEnabled(true);
        this.botonPunto.setEnabled(true);
        this.botonMasMenos.setEnabled(true);
        this.botonRaiz.setEnabled(true);
        return true;
    }

    private void cambiarTamanyo() {
        if (cadenaNumeros.length() > 16) {
            cadenaNumeros = cadenaNumeros.substring(0, 16);
        }

        if (cadenaNumeros.length() < 16) {
            this.entradaNumeros.setFont(new Font("Dialog Bold", Font.BOLD, 36));

        } else {
            entradaNumeros.setFont(new Font("Dialog Bold", Font.BOLD, 28));

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonDEL;
    private javax.swing.JButton botonDivision;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMasMenos;
    private javax.swing.JButton botonMultiplicar;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonRaiz;
    private javax.swing.JButton botonRestar;
    private javax.swing.JButton botonSumar;
    private javax.swing.JLabel entradaNumeros;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel salidaNumeros;
    // End of variables declaration//GEN-END:variables

}
